default: &default
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: arjunparvati
  password: arjunparvati

spec:
  <<: *default
  database: arjunparvati_test

test:
  <<: *default
  database: arjunparvati_test


development:
  <<: *default
  database: arjunparvati_development